# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
machine:
    java:
        version: oraclejdk8
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

    steps:
      - checkout

    dependencies:
        pre:
            cp -avr /licenses $ANDROID_HOME/licenses
            - echo y | android update sdk --no-ui --all --filter extra-google-m2repository,extra-android-support,android-26
            - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-26.0.2

            ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

            - chmod +x gradlew

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
#      - run: gradle test



